### ISSUE TITLE
Applying LBF .nii files to specific ROI

### ISSUE THREAD

**Issue by blairshevlin** [JoramSoch/MACS#14]
Hi,
Thanks for the great toolbox!

I want to see which of two models better explains activity in a given ROI, where I already created a mask for this ROI.

I followed the directions in Section 5 of the manual to generate the information differences between two models. I now have a bunch of .nii files. How would I proceed to evaluate the group IC in a specific ROI? In other words, how can map these .nii files to a ROI, and then extract the IC values? I couldn't find anything in the manual or online, so any help would be appreciated!

**Comment by JoramSoch** [comment]
Dear @blairshevlin,

thanks for your message. Apologies for the late reply, I was on vacation. I see two cases here:

* **Case 1:** You are using information criteria (such as AIC or BIC, as in Sections 4 and 5 of the Manual). In that case, I would run the analysis you did for each participant and then perform a one-sample t-test across the maps `LBF_GLM_1_vs_GLM_2_sub1.nii` from all participants. A positive effect would indicate that `GLM_1` is significantly better than `GLM_2` across the group (vice versa for a negative effect). When interrogating results in SPM, you can use your ROI image to mask the analysis, or you can also extract the mean value in your ROI (see Case 2).

* **Case 2:** You are using cross-validated log model evidences (i.e. cvLME, as in Sections 6ff.). In that case, I would run the analysis from Setion 10 or 11 of the Manual. This will give you group-level results maps (Section 10: group log Bayes factors; Section 11: estimated model frequencies) and you could then report the mean value from the results maps within your ROI images. You could e.g. use the function `spm_extr_ROI_data` from the [spm_helper](https://github.com/JoramSoch/spm_helper) package.

Let me know, if that helps.

Cheers
Joram

**Comment by JoramSoch** [comment]
I close this issue, as the question seems resolved and no particular problem was reported.
